# two node cluster with an ingress-ready control-plane node
# and extra port mappings over 80/443 and 1 worker
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: /dev/null
      containerPath: /var/run/nvidia-container-devices/all
  - role: worker
    extraMounts:
    - hostPath: /dev/null
      containerPath: /var/run/nvidia-container-devices/all